repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer # 修复文件末尾缺失换行
      - id: trailing-whitespace # 清除行尾空格
      - id: check-ast # Python 语法树检查
      - id: check-yaml # 校验 YAML 合法性
      - id: check-case-conflict

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.0
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8]
